#apollo:
#  meta: http://119.45.50.7:8099
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true
#    namespaces: application
#
#app:
#  id: 20200806

server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      loadbalancer:
        use404: true # 路径不匹配返回404 默认503
    #      routes:
    #      - id: cloud-consumer-s
    #        uri: lb://CONSUMER
    #        predicates:
    #        - Path=/api/**
    #        filters:
    #        - StripPrefix=1
#    loadbalancer:
#      ribbon:
#        enabled: false
#  redis:
#    host: ${spring.redis.host}
#    host: 119.45.50.7
#    port: 6379
#    password: Zty&&1212
#    database: 1
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#              POST
#              DELETE
#              PUT
  redis:
    host: 119.45.50.7
    port: 6379
    password: Zty&&1212
    database: 1
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      #      defaultZone: http://localhost:8081/eureka
      defaultZone: http://119.45.50.7:8081/eureka,http://119.45.50.7:8082/eureka

#CONSUMER:
#  ribbon:
#    listOfServers: http://localhost:8084
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule